name: CoinEx Futures Bot

on:
  workflow_dispatch:   # اجرای دستی

jobs:
  run-bot:
    runs-on: ubuntu-latest

    env:
      telegram_token: ${{ secrets.telegram_token }}
      chat_id: ${{ secrets.chat_id }}
      COINEX_API_KEY: ${{ secrets.COINEX_API_KEY }}
      COINEX_API_SECRET: ${{ secrets.COINEX_API_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install ccxt pandas ta requests

      - name: Run trading bot
        run: python main.py
